DROP TABLE IF EXISTS USER;
CREATE TABLE USER(ID BIGINT(19) NOT NULL PRIMARY KEY, BIRTH_DATE TIMESTAMP(26, 6), NAME VARCHAR(255));
DROP TABLE IF EXISTS POST;
CREATE TABLE POST(ID BIGINT(19) NOT NULL PRIMARY KEY, POST VARCHAR(255), USER_ID BIGINT(19) );